language: php

matrix:
  include:
    - php: 7.3
    - php: 7.2
    - php: 7.1

install:
  - composer install --dev --no-interaction

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit -c phpunit.xml.dist

after_success:
  - travis_retry php vendor/bin/php-coveralls